name: web2

services:
  app:
    build: .
    ports:
      - "127.0.0.1:8001:8001"
    environment:
      - FLAG=pascalCTF{REDACTED}
    restart: unless-stopped
    image: web2
    container_name: Web2
